#define HTS_CC "/eep/softwares/miniconda/bin/x86_64-conda_cos6-linux-gnu-cc"
#define HTS_CPPFLAGS "-DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /eep/softwares/miniconda/include"
#define HTS_CFLAGS "-Wall -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /eep/softwares/miniconda/include -fvisibility=hidden"
#define HTS_LDFLAGS "-Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--disable-new-dtags -Wl,--gc-sections -Wl,-rpath,/eep/softwares/miniconda/lib -Wl,-rpath-link,/eep/softwares/miniconda/lib -L/eep/softwares/miniconda/lib -fvisibility=hidden "
#define HTS_LIBS "-ldeflate -llzma -lbz2 -lz -lm  "
