#NGSgenotyp V2.0.0
#number of parallels job by defaut
MaxParallelsJobs: 20

#Maximum graphs per figure for coverage plots
MaxgraphPerFigure: 6

allowed_fasta_params: ['Paralog', 'specie', 'grpRef']
#parameters for plots: [param1, ..., paramN] --> param1: ['excel parameter','bolean operation (<,>,==,<=,>=,!=)','numeric value']
plot_selection_param: [['error rate','<',0.08]]

#Parameters to define genotyp threshold value
genotyp_def_ErrorRate: 0.05
genotyp_alleleProb_THRLD: 0.00001

#Take into account only alignments with 'reads mapped' greater then threshold
reads_mapped_THRLD: 10

#paralog isPositiv alleleprobability threshold
#paralogAlleleProb_THRLD : 0.05

#parameters for genotyp score calculation
#logNormal parameters mean (μ) and standard deviation (σ)
mu : 0.01992734
sigma : 0.01024804
#mu : -4.056581
#sigma : 0.556193

#exponential distribution
#here because of distribution, lbda = 1/(1-"expected value") 108.212560
lbda : 108.212560

#simpson step for integrale calculation
simpson_step: 0.001

#error rate limit for SharedReads xls files
sharedReads_errorRatelim: 0.1

#remove_OldDB : True
#data_dir : DB_DATABASES
#refs_catalog: refs_catalog.p
#ref_dir : REF
#sampleQC_dir: QC_SamplesRef
#all_results_dir: Results
#species_dict : species.yaml

#Log file
log_folder : logs

#Pipeline folders V2
OutFolders:
  bwt_dirResult: BWT_Results
  out_splited: FQ_splited
  out_filtered: FQ_filtered
  main_results_dir: Results
  reference_DB_fld: Refs
  configs_fld: configs
  bwt_IndexdirResult: Refs/BWT_RefIndexes
  single_fasta_ref_fld: Refs/Single_Fastas
  
#config files name
index_cfg: bwt2_index.yaml
KRF_yamlFile: kmerRefFilter_resume.yaml
readsconfig: complete_readsConfig.yaml

#reads filenames
splited_reads: splited_reads.yaml

#results files
xls_shared_reads: shared_reads.xls
putative_alleles: putative_alleles.txt
putative_groups: putative_groups.txt
samtools_stats: samtools_stats.yaml
#MaxSheetNbr: 15
SortKey: 'gscore'
sortOrderReverse: True

xls_headers_titles: {'gscore':'Genotyp Score','error rate':'Error rate', 'mean cover':'Mean Depth','NormDepth':'Normalized Depth', 'Group ID':'Homolog IDs', 'RefLen':'Reference Length (bp)', 'bases mapped (cigar)':'bases mapped', 'mismatches':'mismatches','Region Cov':'Region Coverage','Region':'Analysed Region (bp)','Warnings':'Warnings'}

result_stats_headers: ['gscore','error rate', 'mean cover','NormDepth', 'Group ID', 'RefLen', 'bases mapped (cigar)', 'mismatches','Region Cov','Warnings']

result_stats_headersPaired: ['gscore','error rate', 'mean cover', 'NormDepth','Group ID', 'RefLen', 'reads properly paired', 'bases mapped (cigar)', 'mismatches','Region Cov','Warnings']

seqLen_distrib_graph: RefLen_Distrib.png

#By default pdf reports is desactivated, you should use -pdf option to force pdf generation
generate_pdf_reports: false

#PDF files generation
ERate_MeanCov_PDF: False
Group_ErrMeanCov_PDF: False
ErrRegionCov_PDF: True

#tools relative path
samtools: TOOLS/samtools-1.4/
bowtie2: TOOLS/bowtie2-2.2.6/
fastqc: TOOLS/FastQC_v0_11_4/
picklestats_file: samview_stats.p

picklestats_params: ['reads mapped', 'bases mapped (cigar)', 'mismatches', 'error rate', 'average length', 'average quality']



#splited reads:
out_splited: FQ_Splited
out_splitedReads_yaml: splited_reads_list.yaml

#yaml file with treated reads location
finalReads_yaml: final_reads.yaml

#Bowtie results
bwt_IndexdirResult: 'BWT_RefIndexes'
bwt_build_out: 'bwt-build_out.txt'
bwt_yam_reflist: 'bwt_Reflist.yml'

bwt_dirResult: 'BWT_Results'
#bowtie2_args : ['--phred33', '--minins 0', '--maxins 1000']
bowtie2_args : ['--phred33']

#quality control
GC_interval: [35,60]
seq_min_len: 1000

#quality control results
yml_qc_ref: 'referenceQC.yml'
xls_results_qc : 'referenceQC.xls'
yamlReads_file: 'fastq_ReadsNbr.yml'
fastqc_stdout: fastqc_stdout
fastqc_stderr: fastqc_sterr

#output split_fasta
sep_motif : NNNNN

#species : ['A. halleri', 'A. lyrata']
species : all


ref_id : "Ref_"

#Warnings messages list
Warn_refLen : "Ref. Length"