#halpoAsm v1.0.0
#tools relative path
spades: ../TOOLS/SPAdes-3.11.0/bin/
quast: ../TOOLS/quast-4.5/
yass: ../TOOLS/yass_1.14/
cap3: ../TOOLS/CAP3/
muscle: ../TOOLS/muscle3.8.31/
phyml: ../TOOLS/PhyML-3.1/
bowtie: ../TOOLS/bowtie2-2.2.6/
samtools: ../TOOLS/samtools-1.4/

bwt_dirResult: 'BWT_Results'

#dont forget to insert space at the end of yass parameters
yass_params: '-E 1e-10 -m 10 -s 6 '

float_sep: ','

cov_filter: 10

maxDistContigs: 0.3

qualInsertSizeDevFactor: 1.5

IDgroupColors: {'0':"#F5F6CE",'1':"#BCF5A9",'2':"#A9F5F2",'3':"#BCA9F5",'4':"#F9C2C2",'5':"#EDEF70",'6':"#ADF5E5",'7':"#EBBBF2"}